#
# $Id: GNUmakefile,v 1.1 1999/09/13 11:10:07 kunishi Exp $
#

RELPATH=	links/Choir/Children
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
