#
# $Id: GNUmakefile,v 1.2 2000/10/10 15:40:38 kunishi Exp $
#

INSTFILES=	index.html

INSTFILES_NOBUILD=	apache_pb.png freebsd.png pic00015.jpg pic00076.jpg

include ${SRCTOPDIR}config.mk
include ${SRCTOPDIR}rule.mk
