# 
# $Id: GNUmakefile,v 1.2 1999/12/18 14:24:49 kunishi Exp $
#

INSTFILES+=	index.html

SUBDIR+=	Choir \
		Communication \
		Concour \
		Information \
		Library \
		Org \
		Person

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk

