# 
# $Id: GNUmakefile,v 1.3 2000/10/10 15:40:45 kunishi Exp $
#

INSTFILES+=	index.html

SUBDIR+=	Choir \
		Communication \
		Concour \
		Information \
		Library \
		Org \
		Person

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk

