# 
# $Id: GNUmakefile,v 1.4 2001/01/12 12:03:16 kunishi Exp $
#

USE_NEW_SCHEME=	yes

INSTFILES+=	index.html

SUBDIR+=	Choir \
		Communication \
		Concour \
		Information \
		Library \
		Org \
		Person

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk

