# 
# $Id: Makefile,v 1.1 1999/08/22 16:03:38 kunishi Exp $
# 

RELPATH=	links/Information/Halls
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
