#
# $Id: GNUmakefile,v 1.4 2001/01/12 12:03:39 kunishi Exp $
#

USE_NEW_SCHEME=	yes

INSTFILES=	index.html

INSTFILES_NOBUILD=	apache_pb.png freebsd.png pic00015.jpg pic00076.jpg

include config.mk
include rule.mk
