#
# $Id: GNUmakefile,v 1.1 2000/09/11 11:04:57 kunishi Exp $
#

INSTFILES=	index.html

INSTFILES_NOBUILD=	apache_pb.png freebsd.png pic00015.jpg pic00076.jpg

include ${SRCTOPDIR}config.mk
include ${SRCTOPDIR}rule.mk
