#
# $Id: GNUmakefile,v 1.3 2001/01/09 10:12:23 kunishi Exp $
#

USE_NEW_SCHEME=	yes

INSTFILES=	index.html

INSTFILES_NOBUILD=	apache_pb.png freebsd.png pic00015.jpg pic00076.jpg

include ${SRCTOPDIR}config.mk
include ${SRCTOPDIR}rule.mk
