# 
# $Id: GNUmakefile,v 1.2 1999/08/22 15:15:18 kunishi Exp $
#

RELPATH=	JCA-concours
SRCTOPDIR=	../

INSTFILES+=	index.html

SUBDIR+=	52nd

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
