# 
# $Id: GNUmakefile,v 1.4 2001/02/05 15:03:37 kunishi Exp $
# 

USE_NEW_SCHEME=	yes

INSTFILES+=	aichi.html \
		aomori.html \
		chubu.html \
		chubu2.html \
		chugoku.html \
		fukuoka.html \
		gunma.html \
		highschool.html \
		hokkaido1.html \
		hokkaido2.html \
		index.html \
		kagoshima.html \
		kanagawa.html \
		kansai1.html \
		kansai2.html \
		kansai3.html \
		kanto1.html \
		kanto2-notable.html \
		kanto2.html \
		kyushu.html \
		miyagi.html \
		saitama.html \
		shikoku.html \
		shizuoka.html \
		tickets.html \
		tohoku.html \
		tokyo.html \
		tokyo2.html \
		toyama.html \
		yamagata.html \
		zenkoku1.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk


