# 
# $Id: GNUmakefile,v 1.2 1999/12/18 14:25:10 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Concert \
		Genre \
		Halls \
		Mailinglist

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
