# 
# $Id: GNUmakefile,v 1.3 2000/10/10 15:40:40 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Concert \
		Genre \
		Halls \
		Mailinglist

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
