# 
# $Id: GNUmakefile,v 1.5 2000/10/10 15:40:38 kunishi Exp $
# 

INSTFILES_NOBUILD+=	background.png \
			bg.png \
			chorusroom-toplogo.png

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
