# 
# $Id: GNUmakefile,v 1.4 2000/08/29 10:08:52 kunishi Exp $
# 

INSTFILES_NOBUILD+=	background.png \
			bg.png \
			chorusroom-toplogo.png

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
