# 
# $Id: Makefile,v 1.1 1999/08/22 16:21:41 kunishi Exp $
# 

RELPATH=	image
SRCTOPDIR=	../

INSTFILES_NOBUILD+=	background.gif \
			bg.gif

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
