# 
# $Id: Makefile,v 1.2 1999/09/10 14:53:34 kunishi Exp $
# 

RELPATH=	image
SRCTOPDIR=	../

INSTFILES_NOBUILD+=	background.png \
			bg.png

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
