# 
# $Id: GNUmakefile,v 1.1 1999/08/22 16:04:47 kunishi Exp $
# 

RELPATH=	links/Information/Mailinglist
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
