CREATE DATABASE chorusroom;
USE chorusroom;

CREATE TABLE pref (
       id INTEGER PRIMARY KEY,
       jname ENUM(
       	    '北海道',
	    '青森県','秋田県','岩手県','山形県','宮城県','福島県',
	    '茨城県','千葉県','栃木県','群馬県','埼玉県','東京都','神奈川県',
	    '新潟県','富山県','石川県','福井県','長野県','岐阜県',
	    '山梨県','静岡県','愛知県','三重県',
	    '滋賀県','京都府','大阪府','兵庫県','奈良県','和歌山県',
	    '鳥取県','島根県','岡山県','広島県','山口県',
	    '香川県','徳島県','愛媛県','高知県',
	    '福岡県','佐賀県','長崎県','熊本県','大分県','宮崎県','鹿児島県',
	    '沖縄県','海外','その他'));
INSERT INTO pref (id, jname)
       VALUES (1,'北海道'),
       	      (2,'青森県'),
	      (3,'秋田県'),
	      (4,'岩手県'),
	      (5,'山形県'),
	      (6,'宮城県'),
	      (7,'福島県'),
	      (8,'茨城県'),
	      (9,'栃木県'),
	      (10,'群馬県'),
	      (11,'埼玉県'),
	      (12,'千葉県'),
	      (13,'東京都'),
	      (14,'神奈川県'),
	      (15,'山梨県'),
	      (16,'新潟県'),
	      (17,'富山県'),
	      (18,'石川県'),
	      (19,'福井県'),
	      (20,'長野県'),
	      (21,'岐阜県'),
	      (22,'静岡県'),
	      (23,'愛知県'),
	      (24,'三重県'),
	      (25,'滋賀県'),
	      (26,'京都府'),
	      (27,'大阪府'),
	      (28,'兵庫県'),
	      (29,'奈良県'),
	      (30,'和歌山県'),
	      (31,'鳥取県'),
	      (32,'島根県'),
	      (33,'岡山県'),
	      (34,'広島県'),
	      (35,'山口県'),
	      (36,'香川県'),
	      (37,'徳島県'),
	      (38,'愛媛県'),
	      (39,'高知県'),
	      (40,'福岡県'),
	      (41,'佐賀県'),
	      (42,'長崎県'),
	      (43,'熊本県'),
	      (44,'大分県'),
	      (45,'宮崎県'),
	      (46,'鹿児島県'),
	      (47,'沖縄県'),
	      (48,'海外'),
	      (49,'その他');

CREATE TABLE choir (
       urn VARCHAR(20) PRIMARY KEY,
       name VARCHAR(100) NOT NULL,
       url VARCHAR(100) NOT NULL,
       pref INTEGER, 
       type ENUM('mixed','male','female','same-voice','children') NULL,
       kind ENUM('general','univ','company','children','highschool',
       	    'junior-highschool','senior-highschool','elementary-school') NULL,
       comment TEXT NULL,
       yomi VARCHAR(40) NULL,
       created DATETIME NOT NULL,
       modified TIMESTAMP);
GRANT ALL PRIVILEGES ON chorusroom.* TO 'chorusroom'@'localhost'
      IDENTIFIED BY 'pizzetti';
