#
# $Id: GNUmakefile,v 1.6 2001/01/12 12:03:39 kunishi Exp $
#

INSTFILES_NOBUILD=	NMZ.body \
			NMZ.body.ja \
			NMZ.foot \
			NMZ.foot.ja \
			NMZ.head \
			NMZ.head.ja \
			NMZ.result.normal \
			NMZ.result.normal.ja \
			NMZ.result.short \
			NMZ.result.short.ja \
			NMZ.tips \
			NMZ.tips.ja

include config.mk
include rule.mk
