# 
# $Id: GNUmakefile,v 1.4 2000/10/10 15:40:39 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Children \
		Company \
		General \
		Highschool \
		Link \
		OB \
		Univ

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
