# 
# $Id: GNUmakefile,v 1.3 1999/12/18 14:24:51 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Children \
		Company \
		General \
		Highschool \
		Link \
		OB \
		Univ

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
