# 
# $Id: GNUmakefile,v 1.5 2001/01/12 12:03:16 kunishi Exp $
# 

USE_NEW_SCHEME=	yes

INSTFILES+=	index.html

SUBDIR+=	Children \
		Company \
		General \
		Highschool \
		Link \
		OB \
		Univ

include config.mk
include rule.mk
