#
# $Id: GNUmakefile,v 1.4 2000/10/10 15:40:37 kunishi Exp $
#

INSTFILES_NOBUILD=	NMZ.head.en NMZ.head.ja NMZ.body.en NMZ.body.ja \
			NMZ.foot.en NMZ.foot.ja

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
