#
# $Id: GNUmakefile,v 1.5 2000/11/16 16:36:39 kunishi Exp $
#

INSTFILES_NOBUILD=	NMZ.body \
			NMZ.body.ja \
			NMZ.foot \
			NMZ.foot.ja \
			NMZ.head \
			NMZ.head.ja \
			NMZ.result.normal \
			NMZ.result.normal.ja \
			NMZ.result.short \
			NMZ.result.short.ja \
			NMZ.tips \
			NMZ.tips.ja

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
