#
# $Id: GNUmakefile,v 1.2 1999/09/17 01:40:09 kunishi Exp $
#

RELPATH=	namazu/index
SRCTOPDIR=	../../

INSTFILES_NOBUILD=	NMZ.head.en NMZ.head.ja NMZ.body.en NMZ.body.ja \
			NMZ.foot.en NMZ.foot.ja

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
