#
# $Id: Makefile,v 1.3 1999/12/18 14:25:37 kunishi Exp $
#

INSTFILES_NOBUILD=	NMZ.head.en NMZ.head.ja NMZ.body.en NMZ.body.ja \
			NMZ.foot.en NMZ.foot.ja

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
