#
# $Id: Makefile,v 1.1 1999/09/17 01:00:54 kunishi Exp $
#

RELPATH=	namazu/index
SRCTOPDIR=	../../

INSTFILES_NOBUILD=	NMZ.head.en NMZ.head.ja NMZ.body.en NMZ.body.ja

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
