# 
# $Id: GNUmakefile,v 1.4 2001/01/09 10:12:19 kunishi Exp $
# 

USE_NEW_SCHEME=	yes

INSTFILES+=	choir.html \
		index.html \
		member-homepage.html \
		notice.html \
		whatishml.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
