# 
# $Id: Makefile,v 1.1 1999/08/24 12:38:46 kunishi Exp $
# 

RELPATH=	hml
SRCTOPDIR=	../

INSTFILES+=	choir.html \
		index.html \
		member-homepage.html \
		notice.html \
		whatishml.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
