# 
# $Id: Makefile,v 1.1 1999/08/22 15:32:24 kunishi Exp $
#

RELPATH=	links
SRCTOPDIR=	../

INSTFILES+=	index.html

SUBDIR+=	Choir \
		Communication \
		Concour \
		Information \
		Library \
		Org \
		Person

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk

