# 
# $Id: GNUmakefile,v 1.5 2001/01/03 11:34:52 kunishi Exp $
# 

USE_NEW_SCHEME=	yes

INSTFILES+=	index.html

SUBDIR+=	JCA
SUBDIR+=	KOVOX
SUBDIR+=	NHK
SUBDIR+=	Shiga-VEC
SUBDIR+=	TVEC
SUBDIR+=	Takarazuka

include config.mk
include rule.mk
