# 
# $Id: GNUmakefile,v 1.6 2001/05/06 14:27:57 kunishi Exp $
# 

USE_NEW_SCHEME=	yes

INSTFILES+=	index.html

SUBDIR+=	JCA
SUBDIR+=	KOVOX
SUBDIR+=	KVEC
SUBDIR+=	NHK
SUBDIR+=	Shiga-VEC
SUBDIR+=	TVEC
SUBDIR+=	Takarazuka

include config.mk
include rule.mk
