# 
# $Id: GNUmakefile,v 1.5 2001/01/12 12:03:14 kunishi Exp $
# 

USE_NEW_SCHEME=	yes

INSTFILES+=	choir.html \
		index.html \
		member-homepage.html \
		notice.html \
		whatishml.html

include config.mk
include rule.mk
