# 
# $Id: GNUmakefile,v 1.3 2000/10/10 15:40:38 kunishi Exp $
# 

INSTFILES+=	choir.html \
		index.html \
		member-homepage.html \
		notice.html \
		whatishml.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
