# 
# $Id: GNUmakefile,v 1.2 1999/12/18 14:24:47 kunishi Exp $
# 

INSTFILES+=	choir.html \
		index.html \
		member-homepage.html \
		notice.html \
		whatishml.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
