# 
# $Id: GNUmakefile,v 1.5 2001/01/12 12:03:07 kunishi Exp $
#

USE_NEW_SCHEME=	yes

INSTFILES+=	calendar97.html \
		index.html \
		junior97.html \
		okaasan97.html \
		ticket97-1.html

include config.mk
include rule.mk
