# 
# $Id: GNUmakefile,v 1.4 2001/01/09 10:12:17 kunishi Exp $
#

USE_NEW_SCHEME=	yes

INSTFILES+=	calendar97.html \
		index.html \
		junior97.html \
		okaasan97.html \
		ticket97-1.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
