# 
# $Id: GNUmakefile,v 1.3 2000/10/10 15:40:38 kunishi Exp $
#

INSTFILES+=	calendar97.html \
		index.html \
		junior97.html \
		okaasan97.html \
		ticket97-1.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
