# 
# $Id: GNUmakefile,v 1.2 1999/09/09 04:07:00 kunishi Exp $
# 

RELPATH=	links/Person
SRCTOPDIR=	../../

INSTFILES+=	index.html

SUBDIR+=	Composer \
		Conductor \
		Misc \
		Poet

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
