# 
# $Id: GNUmakefile,v 1.3 1999/12/18 14:25:29 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Composer \
		Conductor \
		Misc \
		Poet

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
