# 
# $Id: GNUmakefile,v 1.4 2000/10/10 15:40:42 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Composer \
		Conductor \
		Misc \
		Poet

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
