# 
# $Id: Makefile,v 1.1 1999/08/22 16:01:13 kunishi Exp $
# 

RELPATH=	links/Information/Concert
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
