# 
# $Id: GNUmakefile,v 1.3 2000/10/10 15:40:42 kunishi Exp $
# 

INSTFILES+=	index.html

SUBDIR+=	Assoc \
		CD \
		Camp \
		Hall \
		Score

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
