# 
# $Id: GNUmakefile,v 1.1 1999/08/22 16:07:28 kunishi Exp $
# 

RELPATH=	links/Org
SRCTOPDIR=	../../

INSTFILES+=	index.html

SUBDIR+=	Assoc \
		CD \
		Camp \
		Hall \
		Score

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
