# 
# $Id: GNUmakefile,v 1.1 1999/08/22 16:02:24 kunishi Exp $
# 

RELPATH=	links/Information/Genre
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
