# 
# $Id: Makefile,v 1.1 1999/08/22 16:22:54 kunishi Exp $
# 

RELPATH=	style
SRCTOPDIR=	../

INSTFILES_NOBUILD=	default.css \
			jca-concour.css \
			toppage.css

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
