# 
# $Id: GNUmakefile,v 1.1 1999/08/24 12:37:32 kunishi Exp $
#

RELPATH=	ajcl
SRCTOPDIR=	../

INSTFILES+=	calendar97.html \
		index.html \
		junior97.html \
		okaasan97.html \
		ticket97-1.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
