# 
# $Id: GNUmakefile,v 1.2 1999/12/18 14:24:46 kunishi Exp $
#

INSTFILES+=	calendar97.html \
		index.html \
		junior97.html \
		okaasan97.html \
		ticket97-1.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
