# 
# $Id: Makefile,v 1.1 1999/08/22 16:17:07 kunishi Exp $
# 

RELPATH=	links/Person/Composer
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
