# 
# $Id: Makefile,v 1.1 1999/08/24 12:28:03 kunishi Exp $
# 

RELPATH=	51st
SRCTOPDIR=	../

INSTFILES+=	aichi.html \
		chiba.html \
		chubu1.html \
		chubu2.html \
		chugoku.html \
		fukuoka.html \
		fukushima.html \
		gifu1.html \
		gifu2.html \
		hiroshima.html \
		hokkaido1.html \
		hokkaido2.html \
		index.html \
		ishikawa.html \
		iwate1.html \
		iwate2.html \
		junior-highschool.html \
		kadaikyoku.html \
		kagoshima.html \
		kanagawa.html \
		kansai1.html \
		kansai2.html \
		kansai3.html \
		kanto1.html \
		kanto2.html \
		kyushu.html \
		mie.html \
		miyagi.html \
		nagano.html \
		saitama.html \
		schedule.html \
		senior-highschool.html \
		shikoku1.html \
		shikoku2.html \
		shimane.html \
		shizuoka.html \
		tohoku.html \
		tokyo1.html \
		yamagata.html \
		yamanashi.html \
		zenkoku1.html \
		zenkoku2.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
