# 
# $Id: Makefile,v 1.1 1999/08/22 15:48:36 kunishi Exp $
# 

RELPATH=	links/Information
SRCTOPDIR=	../../

INSTFILES+=	index.html

SUBDIR+=	Concert \
		Genre \
		Halls \
		Mailinglist

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
