# 
# $Id: GNUmakefile,v 1.1 1999/08/22 16:15:58 kunishi Exp $
# 

RELPATH=	links/Person
SRCTOPDIR=	../../

INSTFILES+=	index.html

SUBDIR+=	Composer \
		Conductor \
		Poet

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
