# 
# $Id: Makefile,v 1.2 1999/09/13 11:08:57 kunishi Exp $
# 

RELPATH=	links/Choir
SRCTOPDIR=	../../

INSTFILES+=	index.html

SUBDIR+=	Children \
		Company \
		General \
		Highschool \
		Link \
		OB \
		Univ

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
