# 
# $Id: Makefile,v 1.1 1999/08/22 15:34:31 kunishi Exp $
# 

RELPATH=	links/Choir
SRCTOPDIR=	../../

INSTFILES+=	index.html

SUBDIR+=	Company \
		General \
		Highschool \
		Link \
		OB \
		Univ

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
