# 
# $Id: GNUmakefile,v 1.1 1999/08/22 15:35:53 kunishi Exp $
#

RELPATH=	links/Choir/Company
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
