# 
# $Id: GNUmakefile,v 1.1 1999/08/24 05:21:53 kunishi Exp $
#

RELPATH=	50th
SRCTOPDIR=	../

INSTFILES+=	aichi.html \
		chubu.html \
		chubu1.html \
		chubu2.html \
		chugoku.html \
		fukushima.html \
		general-a.html \
		general-b.html \
		hokkaido1.html \
		hokkaido2.html \
		index.html \
		ishikawa.html \
		junior.html \
		kagoshima.html \
		kanagawa-1.html \
		kansai1.html \
		kansai2.html \
		kansai3.html \
		kanto.html \
		kochi.html \
		kyushu.html \
		mie.html \
		miyagi.html \
		okayama.html \
		senior.html \
		shikoku.html \
		shizuoka.html \
		ticket.html \
		tohoku-junior.html \
		tohoku-other.html \
		tohoku-senior.html \
		tohoku.html \
		tokyo.html \
		univ-company.html \
		yamagata.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
