# 
# $Id: Makefile,v 1.1 1999/08/23 10:44:43 kunishi Exp $
# 

RELPATH=	48th
SRCTOPDIR=	../

INSTFILES+=	48th-chubu.html \
		48th-chugaku.html \
		48th-chugoku.html \
		48th-hokkaido.html \
		48th-kansai.html \
		48th-kyushu.html \
		48th-precise1.html \
		48th-precise2.html \
		48th-precise3.html \
		48th-precise4.html \
		48th-precise5.html \
		48th-precise6.html \
		48th-result.html \
		48th-shikoku.html \
		48th-tohoku.html \
		48th-tokyo.html \
		48thkanto.html \
		index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
