# 
# $Id: GNUmakefile,v 1.1 1999/08/16 00:53:41 kunishi Exp $
#

RELPATH=	.
SRCTOPDIR=	./

INSTFILES+=	47thajcl.html \
		CDShop.html \
		ajcl-contest.html \
		asian960518.html \
		faq.html \
		gakufuShop.html \
		hyogoEarthquake.html \
		index.html \
		info-note.html \
		info-note2.html \
		kovox.html \
		misc.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
