# 
# $Id: GNUmakefile,v 1.3 1999/08/16 02:50:57 kunishi Exp $
#

RELPATH=	.
SRCTOPDIR=	./

INSTFILES+=	CDShop.html \
		ajcl-contest.html \
		asian960518.html \
		faq.html \
		gakufuShop.html \
		hyogoEarthquake.html \
		index.html \
		info-note.html \
		info-note2.html \
		kovox.html \
		misc.html \
		47thajcl.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
