#
# $Id: mtree.spec,v 1.1 2000/11/13 11:28:00 kunishi Exp $
#
/set type=dir uid=1001 gid=1001 mode=0755
.
    ajcl
    ..
    concours
        JCA
            47th
            ..
            48th
            ..
            49th
            ..
            50th
            ..
            51st
            ..
            52nd
            ..
            53rd
            ..
        ..
        KOVOX
        ..
    ..
    hml
    ..
    image
    ..
    links
        Choir
            Children
            ..
            Company
            ..
            General
            ..
            Highschool
            ..
            Link
            ..
            OB
            ..
            Univ
            ..
        ..
        Communication
        ..
        Concour
        ..
        Information
            Concert
            ..
            Genre
            ..
            Halls
            ..
            Mailinglist
            ..
        ..
        Library
        ..
        Org
            Assoc
            ..
            CD
            ..
            Camp
            ..
            Hall
            ..
            Score
            ..
        ..
        Person
            Composer
            ..
            Conductor
            ..
            Misc
            ..
            Poet
            ..
        ..
    ..
    namazu
        index
        ..
    ..
    server
    ..
    style
    ..
    tech
    ..
    whatsnew
    ..
..
