# 
# $Id: GNUmakefile,v 1.1 1999/08/22 16:18:52 kunishi Exp $
# 

RELPATH=	links/Person/Conductor
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
