# 
# $Id: Makefile,v 1.1 1999/08/22 15:38:25 kunishi Exp $
# 

RELPATH=	links/Choir/Highschool
SRCTOPDIR=	../../../

INSTFILES+=	index.html

include ${SRCTOPDIR}/config.mk
include ${SRCTOPDIR}/rule.mk
